# === Core paths ===
cache_dir: "data/cache"

# === Data to load ===
include_qualifying: true

# === Race model (choose: "ols_team", "ridge_team", "corrections_team") ===
race_model: "ols_team"
regularization_alpha: 1.0        # used only if race_model == "ridge_team"

# === Race model controls (splines & interactions) ===
race_spline_df_tyre_age: 4
race_spline_df_lap_num: 4
race_spline_df_tyre_age_interact: 3
race_use_compound_age_interaction: true

# === Reference points for normalization helpers ===
tyre_ref_compound: "M"           # used by some helpers; safe to leave as-is
tyre_ref_age: 3
fuel_ref_lap: "median"

# === Qualifying (evolution-aware) ===
quali_winsorize: true
quali_winsor_lower_q: 0.00       # no lower trim by default
quali_winsor_upper_q: 0.05       # light upper-tail trim of outliers
quali_use_topk_after_norm: false # use all valid laps after normalization
quali_top_k: 3                   # only used if quali_use_topk_after_norm: true
quali_var_epsilon: 1e-6          # numeric guard for inverse-variance weights

# === Event-level blend (Race + Quali) ===
wR: 0.6
wQ: 0.4
apply_bayes_shrinkage: true

# === Weighting controls ===
weighting:
  recency_mode: "date_half_life"   # "date_half_life" or "event_index"
  event_recency_decay: 0.92        # used if recency_mode == "event_index"
  half_life_days: 120              # used if recency_mode == "date_half_life"
  race_sample_weight: 1.0          # weight per race lap contributing (race_n)
  quali_sample_weight: 1.0         # weight per quali segment contributing (quali_k)

# === Visualization track (for outline helper) ===
viz_track:
  year: 2025
  grand_prix: "Canada"
  session: "R"
