# === Core paths ===
cache_dir: "data/cache"

# === Data to load ===
include_qualifying: true

# === Race model (choose: "ols_team", "ridge_team", "corrections_team") ===
race_model: "ols_team"
regularization_alpha: 1.0        # used only if race_model == "ridge_team"

# === Race model controls (splines & interactions) ===
race_spline_df_tyre_age: 4
race_spline_df_lap_num: 4
race_spline_df_tyre_age_interact: 3
race_use_compound_age_interaction: true

# Optional feature toggles for README "expose all knobs"
race_use_event_fe: true          # include C(event) in race models
race_se_type: "cluster"          # "cluster" (driver_event) or "HC3"
race_cluster_group: "driver_event"

# === Reference points for normalization helpers ===
tyre_ref_compound: "M"           # used by some helpers; safe to leave as-is
tyre_ref_age: 3
fuel_ref_lap: "median"

# === Qualifying (evolution-aware) ===
quali_winsorize: true
quali_winsor_lower_q: 0.00       # no lower trim by default
quali_winsor_upper_q: 0.05       # light upper-tail trim of outliers
quali_use_topk_after_norm: false # use all valid laps after normalization
quali_top_k: 3                   # only used if quali_use_topk_after_norm: true
quali_var_epsilon: 1e-6          # numeric guard for inverse-variance weights
quali_evolution_adjust: true     # keep median-by-segment normalization

# === Event-level blend (Race + Quali) ===
wR: 0.6
wQ: 0.4
apply_bayes_shrinkage: true

# === Weighting controls ===
weighting:
  recency_mode: "date_half_life"   # "date_half_life" or "event_index"
  event_recency_decay: 0.92        # used if recency_mode == "event_index"
  half_life_days: 120              # used if recency_mode == "date_half_life"
  race_sample_weight: 1.0          # weight per race lap contributing (race_n)
  quali_sample_weight: 1.0         # weight per quali segment contributing (quali_k)

# === Shrinkage (EB) ===
shrinkage:
  target: "field_mean"        # "field_mean" | "team_mean" | "zero"
  include_team_re: true       # shrink team means toward field mean first
  prior_var_mode: "moments"   # "moments" (method-of-moments) or "fixed"
  prior_var_fixed: 0.0        # used iff prior_var_mode == "fixed" (seconds^2)
  min_prior_var: 1e-6         # lower bound for tau^2

# === Visualization track (for outline helper) ===
viz_track:
  year: 2025
  grand_prix: "Canada"
  session: "R"

# ===== Equal-car visualization (optional overrides) =====
visualize_equal_race:
  use_event_specific_deltas: true     # use that event’s delta_event if available
  target_gp_substr: "canadian"        # which event file to pull (case-insensitive substring)
  base_lap_sec: 90.0                  # baseline lap time for the sim (seconds)
  n_laps: 20                          # number of laps to simulate
  dt: 0.5                             # timestep (seconds) for animation/sim
  lap_jitter_sd: 0.12                 # lap-to-lap random noise (seconds)
  random_seed: 42                     # seed for reproducibility

# ===== Reliability model =====
reliability:
  mode: "per_race"            # "per_race" (recommended) or "per_lap"
  per_race_dnf: 0.10          # ~10% chance a car DNFs over a typical race
  typical_race_laps: 70       # used to derive per-lap hazard
  # If mode == "per_lap", set:
  # per_lap: 0.0015

# ===== Tyre degradation (compound- & track-type aware) =====
degradation:
  # Optional: sample compounds per driver by mix; else use default_compound
  compound_mix:
    S: 0.25
    M: 0.50
    H: 0.25
  default_compound: "M"

  # Piecewise slopes in seconds per lap and a switch lap
  compounds:
    S: { early_slope: 0.035, late_slope: 0.010, switch_lap: 10 }
    M: { early_slope: 0.020, late_slope: 0.012, switch_lap: 14 }
    H: { early_slope: 0.010, late_slope: 0.015, switch_lap: 18 }

  # Track-type multipliers (heuristic: street vs permanent)
  track_type_multipliers:
    street: 1.15
    permanent: 1.00
    high_deg: 1.25
    low_deg: 0.90

# ===== Overtaking (logistic) =====
overtaking:
  alpha_pace: 6.0                 # effect of normalized pace gap
  beta_drs: 1.5                   # DRS bonus
  gamma_defend: 1.2               # penalty if leader defended earlier
  dirty_air_penalty: 0.15         # baseline difficulty to pass
  drs_detect_thresh_s: 1.0        # DRS detection gap (seconds)
  detection_offset_fraction: 0.03 # detection point upstream of zone start (fraction of lap)
  drs_min_enable_lap: 3           # DRS available after this leader lap (F1-style)
  drs_cooldown_after_sc_laps: 2   # delay after SC in-lap before re-enabling DRS

  # Track-specific overrides by GP substring (case-insensitive)
  track_overrides:
    monaco:
      dirty_air_penalty: 0.35
      drs_detect_thresh_s: 0.8
      alpha_pace: 4.0
    monza:
      dirty_air_penalty: 0.05
      drs_detect_thresh_s: 1.2
      alpha_pace: 7.5

# ===== Starts (T1 variability) =====
starts:
  start_gain_sd: 0.08           # random start gain/loss in seconds (small)
  start_gain_rank_bias: 0.03    # >0 lets mid/back gain a touch on average; 0 for neutral
