# === Core paths ===
cache_dir: "fastf1_cache"

# === Data to load ===
include_qualifying: true
season:
  year: 2025
  include_sprint: true   # controls which weekends to enumerate; we still load Q+R

# ===== Weather (merge + simple temperature effect) =====
weather:
  use: true
  merge_tolerance_seconds: 120   # nearest-time join tolerance
  fields: ["ambient_temp_c", "track_temp_c"]  # what we guarantee to populate (NaN allowed)
  temp_multiplier:               # temperature → tyre degradation scaling (small, bounded)
    enable: true
    base_c: 35           # reference track temperature (°C)
    k_per_15c: 0.08      # +8% deg for each +15°C above base

# ===== Viz (overlays) =====
viz:
  show_weather_overlay: true

# ===== Season Monte Carlo =====
season_simulation:
  runs: 5000
  include_sprint_points: false
  fastest_lap_bonus: true
  random_seed: 42

# === Race model (choose: "ols_team", "ridge_team", "corrections_team") ===
race_model: "ols_team"
regularization_alpha: 1.0        # used only if race_model == "ridge_team"

# === Race model controls (splines & interactions) ===
race_spline_df_tyre_age: 4
race_spline_df_lap_num: 4
race_spline_df_tyre_age_interact: 3
race_use_compound_age_interaction: true

# Optional feature toggles for README "expose all knobs"
race_use_event_fe: true          # include C(event) in race models
race_se_type: "cluster"          # "cluster" (driver_event) or "HC3"
race_cluster_group: "driver_event"

# === Reference points for normalization helpers ===
tyre_ref_compound: "M"           # used by some helpers; safe to leave as-is
tyre_ref_age: 3
fuel_ref_lap: "median"

# === Qualifying (evolution-aware) ===
quali_winsorize: true
quali_winsor_lower_q: 0.00       # no lower trim by default
quali_winsor_upper_q: 0.05       # light upper-tail trim of outliers
quali_use_topk_after_norm: false # use all valid laps after normalization
quali_top_k: 3                   # only used if quali_use_topk_after_norm: true
quali_var_epsilon: 1e-6          # numeric guard for inverse-variance weights
quali_evolution_adjust: true     # keep median-by-segment normalization

# === Event-level blend (Race + Quali) ===
wR: 0.6
wQ: 0.4
apply_bayes_shrinkage: true

# === Weighting controls (legacy; still supported) ===
weighting:
  recency_mode: "date_half_life"   # "date_half_life" or "event_index"
  event_recency_decay: 0.92        # used if recency_mode == "event_index"
  half_life_days: 120              # used if recency_mode == "date_half_life"
  race_sample_weight: 1.0          # weight per race lap contributing (race_n)
  quali_sample_weight: 1.0         # weight per quali segment contributing (quali_k)

# === Shrinkage (Empirical Bayes baseline) ===
shrinkage:
  target: "field_mean"        # "field_mean" | "team_mean" | "zero"
  include_team_re: true       # shrink team means toward field mean first
  prior_var_mode: "fixed"     # "moments" (data-derived) or "fixed" (constant)
  prior_var_fixed: 0.05       # seconds^2; try 0.03–0.07 to adjust strength
  min_prior_var: 1e-6         # lower bound for tau^2

# === Visualization track (for outline helper) ===
viz_track:
  year: 2025
  grand_prix: "Canada"
  session: "R"

# ===== Equal-car visualization (optional overrides) =====
visualize_equal_race:
  use_event_specific_deltas: true
  target_gp_substr: "canadian"
  base_lap_sec: 90.0
  n_laps: 20
  dt: 0.5
  lap_jitter_sd: 0.12
  random_seed: 42

# ===== Reliability model =====
reliability:
  mode: "per_race"
  per_race_dnf: 0.10
  typical_race_laps: 70
  # per_lap: 0.0015  # only if mode == "per_lap"

# ===== Tyre degradation =====
degradation:
  source: "linear"
  compound_scale:
    S: 1.0
    M: 1.0
    H: 1.0
  compound_mix:
    S: 0.25
    M: 0.50
    H: 0.25
  default_compound: "M"
  compounds:
    S: { early_slope: 0.035, late_slope: 0.010, switch_lap: 10 }
    M: { early_slope: 0.020, late_slope: 0.012, switch_lap: 14 }
    H: { early_slope: 0.010, late_slope: 0.015, switch_lap: 18 }
  track_type_multipliers:
    street: 1.15
    permanent: 1.00
    high_deg: 1.25
    low_deg: 0.90

# ===== Overtaking =====
overtaking:
  alpha_pace: 6.0
  beta_drs: 1.5
  gamma_defend: 1.2
  dirty_air_penalty: 0.15
  drs_detect_thresh_s: 1.0
  detection_offset_fraction: 0.03
  drs_min_enable_lap: 3
  drs_cooldown_after_sc_laps: 2
  track_overrides:
    monaco:
      dirty_air_penalty: 0.35
      drs_detect_thresh_s: 0.8
      alpha_pace: 4.0
    monza:
      dirty_air_penalty: 0.05
      drs_detect_thresh_s: 1.2
      alpha_pace: 7.5

# ===== Starts =====
starts:
  start_gain_sd: 0.08
  start_gain_rank_bias: 0.03

# ===== Hierarchical shrinkage =====
use_hierarchical_shrinkage: false

# ===== Driver personality =====
personality:
  use: false
  agg_weight: 1.0
  def_weight: 1.0
  risk_weight: 1.0

# ===== Track effects & downforce =====
track_effects:
  use: true
  mode: "archetype"

downforce_profile:
  use: false

# ===== Aggregation knobs =====
aggregation:
  half_life_days: 120
  per_event_decay: 0.92
  use_date_decay: true

# ===== Event-delta usage =====
event_deltas:
  use_event_specific: false

# ===== Reproducibility & diversity =====
rng:
  seed: 2025
  per_event_stream: true
  per_run_stream: true

simulation:
  runs: 5000
  entropy_guard:
    min_unique_orders: 0.60

# ===== Paths to calibration artifacts =====
paths:
  degradation_params: "outputs/calibration/degradation_params.json"
  overtake_params: "outputs/calibration/overtake_params.json"
  track_meta: "data/track_meta.csv"
  personality: "outputs/calibration/personality.csv"

# ===== Logging & diagnostics =====
logging:
  level: "INFO"
  write_run_log: true
  diagnostics_dir: "outputs/diagnostics"
